boot:
    masters:
      - dsn: browser:browser.360@tcp(10.16.49.113:3306)/test?timeout=5s&readTimeout=6s
        maxConnLifetime: 600
        maxOpenConns: 50
        maxIdleConns: 10

      - dsn: browser:browser.360@tcp(10.16.49.113:3306)/test?timeout=1s&readTimeout=6s
        maxConnLifetime: 600
        maxOpenConns: 50
        maxIdleConns: 10

    slaves:
      - dsn: browser:browser.360@tcp(10.16.49.113:3306)/test?timeout=1s&readTimeout=6s
        maxConnLifetime: 600
        maxOpenConns: 50
        maxIdleConns: 10
