option:
  max: 1024

storage:
 - host: '127.0.0.1'
   port: 6379
   db: 1
   maxConnLifetime: 600
   maxIdle: 120
   maxActive: 20
   connectTimeout: 1000
   readTimeout: 200
   writeTimeout: 500

 - host: '127.0.0.1'
   port: 6380
   db: 1
   maxConnLifetime: 600
   maxIdle: 120
   maxActive: 20
   connectTimeout: 1000
   readTimeout: 200
   writeTimeout: 500

 - host: '127.0.0.1'
   port: 6381
   db: 1
   maxConnLifetime: 600
   maxIdle: 120
   maxActive: 20
   connectTimeout: 1000
   readTimeout: 200
   writeTimeout: 500

 - host: '127.0.0.1'
   port: 6382
   db: 1
   maxConnLifetime: 600
   maxIdle: 120
   maxActive: 20
   connectTimeout: 1000
   readTimeout: 200
   writeTimeout: 500