boot:
  - host: 'localhost'
    port: 6379
    auth: ''
    db: 1
    maxConnLifetime: 600
    maxIdle: 120
    maxActive: 20
    connectTimeout: 1000
    readTimeout: 200
    writeTimeout: 500

  - host: '127.0.0.1'
    port: 6380
    auth: ''
    db: 1
    maxConnLifetime: 600
    maxIdle: 120
    maxActive: 20
    connectTimeout: 1000
    readTimeout: 200
    writeTimeout: 500


